### ISSUE TITLE
JS Error

### ISSUE THREAD

**Issue by liweichen6** [mlntn/pack-o-bot#1]
![20170810_162618](https://user-images.githubusercontent.com/11507468/29190649-f444f658-7de8-11e7-9302-950a6ab3efe2.png)
Version 0.2.0 (First production version)
Immediatly crashes when launch pack-o-bot.exe.
Was able to launch pre-release but it didn't seem to record anything.
Anything else I should offer to help investigate the issue?

**Comment by geraldhiller** [comment]
Thank you so much! You shouldn't even have found it yet :-) We were ready to announce the release and then we had some last minute bugs to fix. We're currently on that. I hope we'll have it fixed in a little while.

**Comment by mlntn** [comment]
@liweichen6 Now that we're officially released, can you please try again? Should have been fixed in 19800523382c3bf259c5794c9db26d552cd3642a.

**Comment by liweichen6** [comment]
Now I can launch the app, but how do I know if it's recording?
It says "Watching for packs..." but that's it. I opened a pack, then checked pitytracker and nothing's there.
I also tried different language settings in HS, but that isn't the issue.

**Comment by mlntn** [comment]
@liweichen6 Did you enter your token from pitytracker?

**Comment by liweichen6** [comment]
@mlntn Yes, entered and saved.

**Comment by geraldhiller** [comment]
You downloaded the app before we had it bug-free. Could you delete the app again and delete your pack-o-bot user folder (either in Application Support on Mac or in AppData on Windows) and then reinstall the app?

**Comment by liweichen6** [comment]
@geraldhiller Is 0.2.1 (released 17 mins ago) the latest one?
I delete the app folder and /AppData/Roaming/pack-o-bot then download this one, but when I launch it, it says needs to be updated.

**Comment by mlntn** [comment]
@liweichen6 Yes it is. The update check is fixed now.

**Comment by liweichen6** [comment]
This is pretty weird. I still can't get it working.
Shows "Watching for packs..." and that's it.
Even tried to regenerate a new token and still the same.

**Comment by liweichen6** [comment]
`{"region":"xx","unsentPacks":{}}`
This is from packs.json under AppData. Does that mean the bot didn't get any data (not even the region)?

**Comment by geraldhiller** [comment]
Yes. It looks like something went wrong with the setup. Did you close HS before opening Pack-o-Bot? If logging isn't enabled in HS already, POB will enable it in its setup routine, that's why HS needs to be closed, or at least restartet after starting POB. There is no way around it.

**Comment by liweichen6** [comment]
@geraldhiller Yes I tried several times, even restarted my PC.
And anyway to make sure logging is enabled? Like "Logs" folder under Hearthstone?

**Comment by mlntn** [comment]
@liweichen6 Yes, can you please paste the contents of %USERPROFILE%\AppData\Local\Blizzard\Hearthstone\log.config

**Comment by liweichen6** [comment]
[Achievements]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
Verbose=true

[Arena]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
Verbose=true

[FullScreenFX]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
Verbose=true

[LoadingScreen]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
Verbose=true

[Power]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
Verbose=true

[Rachelle]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
Verbose=true

[Zone]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
Verbose=true

[BattleNet]
LogLevel=1
FilePrinting=true

**Comment by mlntn** [comment]
Hmm, I'm not sure what Verbose Achievement logging looks like. Can you post your Achievements.log? It's in C:\Program Files (x86)\Hearthstone\Logs\

**Comment by liweichen6** [comment]
Achievements.log

D 20:03:14.5852494 Validating achieve: 67
D 20:03:14.5877560 NetCache.OnProfileNotices(): sending notices to AdventureProgressMgr::OnNewNotices
D 20:03:14.5882572 NetCache.OnProfileNotices(): sending notices to AchieveManager::OnNewNotices
D 20:03:14.5882572 NetCache.OnProfileNotices(): sending notices to GenericRewardChestNoticeManager::OnNewNotices
D 20:03:14.5892600 NetCache.OnProfileNotices(): sending notices to AccountLicenseMgr::OnNewNotices
D 20:03:14.5892600 NetCache.OnProfileNotices(): sending notices to FixedRewardsMgr::OnNewNotices
D 20:03:14.5917666 NetCache.OnProfileNotices(): sending notices to PopupDisplayManager::OnNewNotices
D 20:03:14.5917666 NetCache.OnProfileNotices(): sending notices to DialogManager::OnNewNotices
D 20:03:14.5922679 NetCache.OnProfileNotices(): sending notices to StoreManager::OnNewNotices
D 20:03:14.5927694 NetCache.OnProfileNotices(): sending notices to GeneralStorePacksPane::OnNewNotices
D 20:03:14.5927694 NetCache.OnProfileNotices(): sending notices to AdventureProgressMgr::OnNewNotices
D 20:03:14.5927694 NetCache.OnProfileNotices(): sending notices to AchieveManager::OnNewNotices
D 20:03:14.5927694 NetCache.OnProfileNotices(): sending notices to GenericRewardChestNoticeManager::OnNewNotices
D 20:03:14.5927694 NetCache.OnProfileNotices(): sending notices to AccountLicenseMgr::OnNewNotices
D 20:03:14.5927694 NetCache.OnProfileNotices(): sending notices to FixedRewardsMgr::OnNewNotices
D 20:03:14.5927694 NetCache.OnProfileNotices(): sending notices to PopupDisplayManager::OnNewNotices
D 20:03:14.5927694 NetCache.OnProfileNotices(): sending notices to DialogManager::OnNewNotices
D 20:03:14.5927694 NetCache.OnProfileNotices(): sending notices to StoreManager::OnNewNotices
D 20:03:14.5927694 NetCache.OnProfileNotices(): sending notices to GeneralStorePacksPane::OnNewNotices
D 20:03:16.0706979 Validating achieve: 60
D 20:03:21.7748612 PopupDisplayManager: adding 0 rewards to load total=0
D 20:03:21.7748612 PopupDisplayManager: Calling AllAchievesShownListeners callbacks
D 20:03:42.7962409 PopupDisplayManager: adding 0 rewards to load total=0
D 20:03:46.7803316 NotifyOfCardGained: [name=Drain Soul cardId=ICC_055 type=SPELL] NORMAL 20
D 20:03:46.7808329 NotifyOfCardGained: [name=Breath of Sindragosa cardId=ICC_836 type=SPELL] NORMAL 18
D 20:03:46.7808329 NotifyOfCardGained: [name=Eternal Servitude cardId=ICC_213 type=SPELL] NORMAL 6
D 20:03:46.7808329 NotifyOfCardGained: [name=Acolyte of Agony cardId=ICC_212 type=MINION] NORMAL 9
D 20:03:46.7808329 NotifyOfCardGained: [name=Howlfiend cardId=ICC_218 type=MINION] NORMAL 12
D 20:03:53.5984555 NotifyOfCardGained: [name=Spirit Lash cardId=ICC_802 type=SPELL] NORMAL 24
D 20:03:53.5984555 NotifyOfCardGained: [name=Roll the Bones cardId=ICC_201 type=SPELL] NORMAL 10
D 20:03:53.5984555 NotifyOfCardGained: [name=Shadowblade cardId=ICC_850 type=WEAPON] GOLDEN 2
D 20:03:53.5984555 NotifyOfCardGained: [name=Drain Soul cardId=ICC_055 type=SPELL] NORMAL 21
D 20:03:53.5984555 NotifyOfCardGained: [name=Sanguine Reveler cardId=ICC_903 type=MINION] NORMAL 23
D 20:04:01.6498586 PopupDisplayManager: adding 0 rewards to load total=0

**Comment by liweichen6** [comment]
And my HS is not located in default location. It's under D://
Does it matter?

**Comment by mlntn** [comment]
Yep, that's the problem. I'll see if we can come up with a solution for that.

**Comment by liweichen6** [comment]
@mlntn Move HS to the default location. Now everything works.
Can't believe it's that simple lol.

**Comment by mlntn** [comment]
Awesome, thanks for all your help debugging this issue. We're working on making this tool more robust and your early feedback helps us tremendously.

**Comment by liweichen6** [comment]
Just found a new bug related to HS language setting.
zh-CN: only the 1st pack is recorded.
en-US: no issues.

**Comment by Ekkstein** [comment]
Hmm, can you send us the email of your pitytracker account via the feedback button on pitytracker?

**Comment by liweichen6** [comment]
@Ekkstein Just sent.

**Comment by Ekkstein** [comment]
It appears that you only have packs from the us server in our database. 
Please login (start hs) to the account (region) from where you have issues posting your packs and post the first line of C:\Program Files (x86)\Hearthstone\LogsBattleNet.log here.

**Comment by liweichen6** [comment]
@Ekkstein I only have an US account, but sometimes I play in zh-CN. It's the HS language setting, not the region.

**Comment by mlntn** [comment]
@liweichen6 Can you paste a copy of Achievements.log with a pack opened while in zh-CN?

**Comment by liweichen6** [comment]
D 22:02:30.3199889 Validating achieve: 67
D 22:02:30.3224955 NetCache.OnProfileNotices(): sending notices to AdventureProgressMgr::OnNewNotices
D 22:02:30.3224955 NetCache.OnProfileNotices(): sending notices to AchieveManager::OnNewNotices
D 22:02:30.3224955 NetCache.OnProfileNotices(): sending notices to GenericRewardChestNoticeManager::OnNewNotices
D 22:02:30.3239995 NetCache.OnProfileNotices(): sending notices to AccountLicenseMgr::OnNewNotices
D 22:02:30.3239995 NetCache.OnProfileNotices(): sending notices to FixedRewardsMgr::OnNewNotices
D 22:02:30.3265061 NetCache.OnProfileNotices(): sending notices to PopupDisplayManager::OnNewNotices
D 22:02:30.3265061 NetCache.OnProfileNotices(): sending notices to DialogManager::OnNewNotices
D 22:02:30.3270077 NetCache.OnProfileNotices(): sending notices to StoreManager::OnNewNotices
D 22:02:30.3275099 NetCache.OnProfileNotices(): sending notices to GeneralStorePacksPane::OnNewNotices
D 22:02:30.3275099 NetCache.OnProfileNotices(): sending notices to AdventureProgressMgr::OnNewNotices
D 22:02:30.3275099 NetCache.OnProfileNotices(): sending notices to AchieveManager::OnNewNotices
D 22:02:30.3275099 NetCache.OnProfileNotices(): sending notices to GenericRewardChestNoticeManager::OnNewNotices
D 22:02:30.3280100 NetCache.OnProfileNotices(): sending notices to AccountLicenseMgr::OnNewNotices
D 22:02:30.3280100 NetCache.OnProfileNotices(): sending notices to FixedRewardsMgr::OnNewNotices
D 22:02:30.3280100 NetCache.OnProfileNotices(): sending notices to PopupDisplayManager::OnNewNotices
D 22:02:30.3280100 NetCache.OnProfileNotices(): sending notices to DialogManager::OnNewNotices
D 22:02:30.3280100 NetCache.OnProfileNotices(): sending notices to StoreManager::OnNewNotices
D 22:02:30.3280100 NetCache.OnProfileNotices(): sending notices to GeneralStorePacksPane::OnNewNotices
D 22:02:31.1486917 Validating achieve: 60
D 22:02:36.7280231 PopupDisplayManager: adding 0 rewards to load total=0
D 22:02:36.7285241 PopupDisplayManager: Calling AllAchievesShownListeners callbacks
D 22:02:57.5624089 PopupDisplayManager: adding 0 rewards to load total=0
D 22:03:00.0535308 NotifyOfCardGained: [name=黑暗裁决 cardId=ICC_039 type=SPELL] NORMAL 16
D 22:03:00.0540321 NotifyOfCardGained: [name=装死 cardId=ICC_052 type=SPELL] NORMAL 21
D 22:03:00.0540321 NotifyOfCardGained: [name=咆哮魔 cardId=ICC_218 type=MINION] NORMAL 15
D 22:03:00.0540321 NotifyOfCardGained: [name=正义保护者 cardId=ICC_038 type=MINION] NORMAL 24
D 22:03:00.0540321 NotifyOfCardGained: [name=命运骨骰 cardId=ICC_201 type=SPELL] NORMAL 11
D 22:03:10.6055806 PopupDisplayManager: adding 0 rewards to load total=0

**Comment by liweichen6** [comment]
Bot shows "found a pack...", "uploading...", then "watching for packs..."
Checked PityTracker but this pack isn't on there.
Does the bot read CardName or CardID?

**Comment by mlntn** [comment]
That pack uploaded for me. Can you confirm that it's not showing out of order in the table of packs here? https://pitytracker.com/packs

**Comment by liweichen6** [comment]
I think I find out why.
I assumed the first shown on PT was the last I uploaded.
But it actually shows between No.20 and No.21.
Bot did upload that one, but I didn't see so I manually add that again.

![20170810_223734](https://user-images.githubusercontent.com/11507468/29199651-9ec5a23e-7e1c-11e7-8bd2-83eaccbccd15.png)
![20170810_223742](https://user-images.githubusercontent.com/11507468/29199654-a0939300-7e1c-11e7-9340-3001a43917a9.png)

**Comment by mlntn** [comment]
@Ekkstein Do you want to take a look at that on PT?

**Comment by mlntn** [comment]
@liweichen6 Thanks again. I'm going to close this ticket. Feel free to open another if you run into another bug.
