### ISSUE TITLE
Doesn't work since the Kobolds and Catacombs release

### ISSUE THREAD

**Issue by davidschwegler** [mlntn/pack-o-bot#11]
On the first try it give a script error once saying something was undefined. After restarting everything, the next time it got stuck on "pack found" and then upon restart again was stuck in a loop of trying to upload and failing.

@mlntn Can you please fix this up for us? Thank you! :) This is an awesome tool that makes pack openings much more fun.

**Comment by geraldhiller** [comment]
We had a small bug on the server side that we fixed roughly an hour after release. It should work now. Did you check again?

**Comment by davidschwegler** [comment]
It still appears to be stuck in a loop. Perhaps something is wrong with some cached data that it's trying to upload. How can I uninstall and start fresh? Do I need to kill some registry key?

**Comment by mlntn** [comment]
@davidschwegler There's no registry key, but there are some config files. Should be in %APPDATA%\Roaming\pack-o-bot

**Comment by davidschwegler** [comment]
Thanks, clearing %APPDATA%\pack-o-bot (%APPDATA%\ is already the Roaming folder on Win10) fixed the issue.

**Comment by mlntn** [comment]
Huh, you’re right about %APPDATA%. I should have checked it on my PC first. It seems wrong that it goes to Roaming. Oh well, glad you got it fixed!
